### ISSUE TITLE
Define location of Dockerfile?

### ISSUE THREAD

**Issue by davoutuk** [spotify/dockerfile-maven#121]
By experimentation I've found that with this maven plugin the 'Dockerfile' has to exist in the same folder as the pom.xml

Is there any way to define a different source folder for the Dockerfile?

**Comment by mattnworb** [comment]
You can change the context directory with this parameter, the Dockerfile must be at the root of it:

https://github.com/spotify/dockerfile-maven/blob/c103ae9a7be1538687cf8f90158c81bdaa341a5d/plugin/src/main/java/com/spotify/plugin/dockerfile/BuildMojo.java#L48-L54

#117 exists for changing the location of the Dockerfile _within_ a context directory

**Comment by davoutuk** [comment]
If I set 
					<contextDirectory>src/main/docker</contextDirectory>
... then the image build fails....

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building eis-config-server 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- dockerfile-maven-plugin:1.3.7:build (default-cli) @ eis-config-server ---
[INFO] Building Docker context D:\Ian\Documents\github\eis-config-server\src\main\docker
[INFO] 
[INFO] Image will be built as davout/eis-config-server:latest
[INFO] 
[INFO] Step 1/5 : FROM openjdk:8-jdk-alpine
[INFO] Pulling from library/openjdk
[INFO] Digest: sha256:006bf9d576f299fecad061bd5e6df6585b022aa0a6da205b16a4a6e223e5a23d
[INFO] Status: Image is up to date for openjdk:8-jdk-alpine
[INFO]  ---> 3642e636096d
[INFO] Step 2/5 : VOLUME /tmp
[INFO]  ---> Using cache
[INFO]  ---> 93e607e40725
[INFO] Step 3/5 : ARG JAR_FILE
[INFO]  ---> Using cache
[INFO]  ---> bb4e69e2b848
[INFO] Step 4/5 : ADD ${JAR_FILE} app.jar
[ERROR] ADD failed: stat /var/lib/docker/tmp/docker-builder687816003/target/eis-config-server-0.0.1-SNAPSHOT.jar: no such file or directory
[WARNING] An attempt failed, will retry 1 more times
org.apache.maven.plugin.MojoExecutionException: Could not build image
	at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:185)
	at com.spotify.plugin.dockerfile.BuildMojo.execute(BuildMojo.java:105)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.tryExecute(AbstractDockerMojo.java:246)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.execute(AbstractDockerMojo.java:235)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: com.spotify.docker.client.exceptions.DockerException: ADD failed: stat /var/lib/docker/tmp/docker-builder687816003/target/eis-config-server-0.0.1-SNAPSHOT.jar: no such file or directory
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.handleError(LoggingProgressHandler.java:105)
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.progress(LoggingProgressHandler.java:63)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1406)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1365)
	at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:178)
	... 26 more
[INFO] Building Docker context D:\Ian\Documents\github\eis-config-server\src\main\docker
[INFO] 
[INFO] Image will be built as davout/eis-config-server:latest
[INFO] 
[INFO] Step 1/5 : FROM openjdk:8-jdk-alpine
[INFO] Pulling from library/openjdk
[INFO] Digest: sha256:006bf9d576f299fecad061bd5e6df6585b022aa0a6da205b16a4a6e223e5a23d
[INFO] Status: Image is up to date for openjdk:8-jdk-alpine
[INFO]  ---> 3642e636096d
[INFO] Step 2/5 : VOLUME /tmp
[INFO]  ---> Using cache
[INFO]  ---> 93e607e40725
[INFO] Step 3/5 : ARG JAR_FILE
[INFO]  ---> Using cache
[INFO]  ---> bb4e69e2b848
[INFO] Step 4/5 : ADD ${JAR_FILE} app.jar
[ERROR] ADD failed: stat /var/lib/docker/tmp/docker-builder658040774/target/eis-config-server-0.0.1-SNAPSHOT.jar: no such file or directory
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.096 s
[INFO] Finished at: 2018-01-04T14:36:09+00:00
[INFO] Final Memory: 30M/415M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.3.7:build (default-cli) on project eis-config-server: Could not build image: ADD failed: stat /var/lib/docker/tmp/docker-builder658040774/target/eis-config-server-0.0.1-SNAPSHOT.jar: no such file or directory -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1

**Comment by mattnworb** [comment]
The context directory is the directory sent from your local machine to the docker daemon to perform the build. If you set it to `src/main/docker` then the output of your maven build (which is under `target` somewhere likely) won't be set to the daemon and won't be visible in the build. 

It sounds like what you really want is what is proposed in #117 and #89 which are not resolved yet.

**Comment by ptahchiev** [comment]
This project is awesome :))) As @davoutuk said most of us try to configure this stuff "by experimentation", then you realize it forces you to follow some predefined build structure, and place your `Dockerfile` next to your `pom.xml` and to top it all the one issue that deals with this (#117) get closed after a few months of discussion as being "a stale issue". Oh, and not to forget that the "old" https://github.com/spotify/docker-maven-plugin supports all this, but somehow recommends you to upgrade to this "new one". Open-source at it's finest.

**Comment by mattnworb** [comment]
@ptahchiev see #89

**Comment by Steve-Dillon** [comment]
I'm getting the following error:

STEP 6: ADD ${JAR_FILE} party.jar
error: build error: error building at STEP "ADD ${JAR_FILE} party.jar": no files found matching "/tmp/build/inputs/src/build/libs/Party*.jar": no such file or directory

My Dockerfile is in a totally different directory and when i try to tun it in Openshift OKD adding it to an existing project it fails.
 i have the following lines of code relating to it in the Dockerfile:
ARG JAR_FILE=build/libs/Party*.jar - basically i'm assuming build file in this directory.
ADD ${JAR_FILE} party.jar - Add this file from the directory above to the the directory workdir below. 
WORKDIR /opt/partyApi

Any ideas why it is failing to find the jar file. This is killing me so any help is very much appreciated.
