### ISSUE TITLE
manifest for <image>:<tag> not found

### ISSUE THREAD

**Issue by Marschupp** [spotify/dockerfile-maven#138]
Hello,
I've got a project that build to images. The structure is something like that:
* Project
  * pom.xml
  * Project Image 1
    * pom.xml
    * Dockerfile -> `<name>:<tag>` = image1:1.0-SNAPSHOT
  * Project Image 2
    * pom.xml
    * Dockerfile -> FROM image1:1.0-SNAPSHOT

As you see, the second image depends on the first image. I use the _com.spotify:dockerfile-maven-plugin:1.3.7_ to build the Dockerfiles. When I execute an `mvn install`, I got:
* root pom, no problem, get deployed to local .m2
* image 1, no problem, get deployed to local docker repo
* image 2, error.

The error I get is:
>  manifest for image1:1.0-SNAPSHOT not found

On the same _Dockerfile_, if I perform a `docker build .`, it builds. What is that manifest thing? 

Stacktrace:
>org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:dockerfile-maven-plugin:1.3.7:build (BuildDocker) on project image2: Could not build image
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Could not build image
        at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:185)
        at com.spotify.plugin.dockerfile.BuildMojo.execute(BuildMojo.java:105)
        at com.spotify.plugin.dockerfile.AbstractDockerMojo.tryExecute(AbstractDockerMojo.java:246)
        at com.spotify.plugin.dockerfile.AbstractDockerMojo.execute(AbstractDockerMojo.java:235)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: com.spotify.docker.client.exceptions.DockerException: manifest for image1:1.0-SNAPSHOT not found
        at com.spotify.plugin.dockerfile.LoggingProgressHandler.handleError(LoggingProgressHandler.java:105)
        at com.spotify.plugin.dockerfile.LoggingProgressHandler.progress(LoggingProgressHandler.java:63)
        at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1406)
        at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1365)
        at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:178)
        ... 25 more

**Comment by dulvac** [comment]
Just ran into this. Same exact issue.

**Comment by mattnworb** [comment]
What does the dockerfile-maven-plugin-related section of your pom.xml's look like?

**Comment by dulvac** [comment]
I seems https://github.com/spotify/dockerfile-maven/issues/55 is related.
