### ISSUE TITLE
Pull from store/oracle/serverjre

### ISSUE THREAD

**Issue by TaekSoonJang** [spotify/dockerfile-maven#16]
I've added store/oracle/serverjre(https://store.docker.com/images/oracle-serverjre-8) to my personal catalog and it works perfectly on local machine using command line like below:
`docker run --rm store/oracle/serverjre:8 java -version`

However, when building maven project based from the image above with this plugin, it fails to pull `store/oracle/serverjre` image. Any suggestion?

```
[INFO] Step 1/6 : FROM store/oracle/serverjre:8
[ERROR] repository store/oracle/serverjre not found: does not exist or no pull access
[WARNING] An attempt failed, will retry 1 more times
org.apache.maven.plugin.MojoExecutionException: Could not build image
	at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:159)
	at com.spotify.plugin.dockerfile.BuildMojo.execute(BuildMojo.java:91)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.tryExecute(AbstractDockerMojo.java:206)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.execute(AbstractDockerMojo.java:195)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.spotify.docker.client.exceptions.DockerException: repository store/oracle/serverjre not found: does not exist or no pull access
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.handleError(LoggingProgressHandler.java:106)
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.progress(LoggingProgressHandler.java:64)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1162)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1111)
	at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:152)
	... 25 more
```

**Comment by mattnworb** [comment]
Probably same cause as #8

**Comment by mattnworb** [comment]
v1.3.0 of the plugin adds support for reading the authentication info from your `~/.dockercfg` or `~/.docker/config.json` file. If you upgrade to that version of the plugin does your build work?

**Comment by TaekSoonJang** [comment]
@mattnworb 
Hi Matt! Unfortunately it's still not working. Does it work also well with credsStore?

**Comment by freesoft** [comment]
@TaekSoonJang  Check if https://github.com/moby/moby/issues/22910 and https://github.com/moby/moby/pull/23100 are related to your issue. I feel like it's not dockerfile-maven plugin issue.
