### ISSUE TITLE
Can build image with aws repository tag

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [spotify/dockerfile-maven#183]
**BUG REPORT**:

## Description

I am trying to build docker image for ECR, but got exception instead.

## How to reproduce
Here is plugin definition:
```
            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>dockerfile-maven-plugin</artifactId>
                <version>1.4.1-SNAPSHOT</version>
                <executions>
                    <execution>
                        <id>default</id>
                        <goals>
                            <goal>build</goal>
                            <goal>push</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <repository>000000000000.dkr.ecr.us-east-1.amazonaws.com/yyy-x-mmmmm-0000000000000:latest</repository>
                    <tag>000000000000.dkr.ecr.us-east-1.amazonaws.com/yyy-x-mmmmm-0000000000000:latest</tag>
                    <contextDirectory>${project.build.directory}</contextDirectory>
                    <googleContainerRegistryEnabled>false</googleContainerRegistryEnabled>
                </configuration>
            </plugin>
```

I execute `mvn clean package`

## What do you expect

Docker image is build.

## What happened instead

I got en error.

## Special note

Please note that when I run from command line:
```
docker build -t 000000000000.dkr.ecr.us-east-1.amazonaws.com/yyy-x-mmmmm-0000000000000:latest .
aws ecr get-login --region us-east-1 --no-include-email
docker push 000000000000.dkr.ecr.us-east-1.amazonaws.com/yyy-x-mmmmm-0000000000000:latest
```

1. Everuthing **works**! E.g. problem is not in docker tag restriction but somewhere in client or plugin.
2. Look at [this issue](https://github.com/moby/moby/issues/25599) here the same error and same problem (I think).

## Software:

- `docker version`: Client - Docker version 18.03.1-ce, build 9ee9f40, Server - Version 18.03.1-ce-win65 (17513)
- Spotify's dockerfile-maven version: 1.4.1-SNAPSHOT

## Full backtrace

```
[WARNING] An attempt failed, will retry 1 more times
org.apache.maven.plugin.MojoExecutionException: Could not build image
	at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:185)
	at com.spotify.plugin.dockerfile.BuildMojo.execute(BuildMojo.java:105)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.tryExecute(AbstractDockerMojo.java:253)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.execute(AbstractDockerMojo.java:242)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST http://localhost:2375/build?pull=true&t=000000000000.dkr.ecr.us-east-1.amazonaws.com%2Fyyy-x-mmmmm-0000000000000%3Alatest%3A000000000000.dkr.ecr.us-east-1.amazonaws.com%2Fyyy-x-mmmmm-0000000000000%3Alatest%3Alatest: 500, body: {"message":"invalid reference format"}

	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2715)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2665)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1428)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1400)
	at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:178)
	... 26 more
Caused by: com.spotify.docker.client.shaded.javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1020)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:816)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:773)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:198)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:79)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

```

## Fix comment

I am trying to implement ECR auth for your plugin. So build tags should be in that sormat. I need it so much - if you have no time, but know "where to see" or start investigation on error it would the best to leave a comment so I can try to fix this by myself and then implement ECR auth for aws.

Thanks!

**Comment by C-h-e-r-r-y** [comment]
I have change configuration to 

```
    <repository>000000000000.dkr.ecr.us-east-1.amazonaws.com/yyy-x-mmmmm-0000000000000</repository>
    <tag>latest</tag>
```

And everything become working. Sorry to bothering. :(
