### ISSUE TITLE
Authentication not working when FROM image is from private repo using encrypted password in settings.xml.

### ISSUE THREAD

**Issue by blindenvy** [spotify/dockerfile-maven#204]
BUG REPORT

## Description

Plugin fails to build a docker image when the base image is being pulled from a private docker repository (hosted on artifactory) when using the `useMavenSettingsForAuth` set to `true` and also using an encrypted maven password (Yes I'm using v1.4.3).

My Configuration is:
```
			<plugin>
				<groupId>com.spotify</groupId>
				<artifactId>dockerfile-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>docker-build-image</id>
						<phase>compile</phase>
						<goals>
							<goal>build</goal>
						</goals>
					</execution>
					<execution>
						<id>docker-push-image-artifactory</id>
						<phase>deploy</phase>
						<goals>
							<goal>push</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<noCache>true</noCache>
					<verbose>true</verbose>
					<contextDirectory>${project.build.directory}/docker</contextDirectory>
					<repository>host.company.com/image-name</repository>
					<tag>${project.version}</tag>
					<retryCount>0</retryCount>
					<dockerInfoDirectory>${project.build.directory}/docker-info</dockerInfoDirectory>
					<useMavenSettingsForAuth>true</useMavenSettingsForAuth>
					<googleContainerRegistryEnabled>false</googleContainerRegistryEnabled>
				</configuration>
			</plugin>
		</plugins>
```

## How to reproduce

Use the plugin to build a docker image which pulls its base image from a private repository with the `useMavenSettingsForAuth` property set to `true`. Furthermore ensure the maven settings are using an encrypted password.

**NOTE**: This issue only occurs when an encrypted password is being used. If I use a non-encrypted password in `settings.xml` it works fine. It would appear that the plugin is not properly decrypting the password when pulling a base image.

**NOTE**: The same setup works fine to push a built image. IE. The plugin correctly decrypts the encrypted password before trying to do a push.

## What do you expect

I would expect for the build command to properly pull the base image from the private repository.

## What happened instead

The plugin fails to download the image with the error:

```
Caused by: com.spotify.docker.client.exceptions.DockerException: Get https://host.company.com/v2/entity/some-image/manifests/1.0.1-SNAPSHOT: unauthorized: BAD_CREDENTIAL
```

NOTE: I know that the credentials are valid as I can successfully push an image using the same credentials.

See full trace below.

## Software:

- `docker version`: 
```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```
- Spotify's dockerfile-maven version: 1.4.3

## Full backtrace

```
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.3:build (docker-build-image) on project my-docker-image: Could not build image: Get https://host.company.com/v2/entity/some-image/manifests/1.0.1-SNAPSHOT: unauthorized: BAD_CREDENTIAL -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.3:build (docker-build-image) on project my-docker-image: Could not build image
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Could not build image
	at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:185)
	at com.spotify.plugin.dockerfile.BuildMojo.execute(BuildMojo.java:105)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.tryExecute(AbstractDockerMojo.java:252)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.execute(AbstractDockerMojo.java:241)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: com.spotify.docker.client.exceptions.DockerException: Get https://host.company.com/v2/entity/some-image/manifests/1.0.1-SNAPSHOT: unauthorized: BAD_CREDENTIAL
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.handleError(LoggingProgressHandler.java:105)
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.progress(LoggingProgressHandler.java:63)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1443)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1402)
	at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:178)
	... 25 more
```

**Comment by blindenvy** [comment]
This problem has been addressed by the `1.4.4` release. Thanks @davidxia for the quick turn around.
