### ISSUE TITLE
Build arguments in dockerfile doesn't support values with spaces

### ISSUE THREAD

**Issue by mplescano** [spotify/dockerfile-maven#211]
I have this in my docker file:
EXPOSE ${EXPOSED_PORT}

and I want to pass this value in my build process
```
    <properties>
        <docker.image.exposed.port><![CDATA[80 9001]]></docker.image.exposed.port>
    </properties>
```
In the plugin I have this snip configured:
```
                            <buildArgs>
                                <EXPOSED_PORT>${docker.image.exposed.port}</EXPOSED_PORT>
                            </buildArgs>
```
But, docker server is complaining about this:
[INFO] Step 10/11 : EXPOSE ${EXPOSED_PORT}
[INFO] 
[ERROR] Invalid containerPort: 80+9001
[WARNING] An attempt failed, will retry 1 more times
org.apache.maven.plugin.MojoExecutionException: Could not build image

If I do this:

docker build --build-arg EXPOSED_PORT="80 9001"-t mplescano/everest-reminder-server-oauth:1.1.0 .

Docker accepts my request.

can you fix it?

Regards

Build arguments in dockerfile doesn't support values with spaces

## Description
Build arguments in dockerfile doesn't support values with spaces
## How to reproduce
I have this in my docker file:
EXPOSE ${EXPOSED_PORT}

and I want to pass this value in my build process
```
    <properties>
        <docker.image.exposed.port><![CDATA[80 9001]]></docker.image.exposed.port>
    </properties>
```
In the plugin I have this snip configured:
```
                            <buildArgs>
                                <EXPOSED_PORT>${docker.image.exposed.port}</EXPOSED_PORT>
                            </buildArgs>
```

But, docker server is complaining about this:
[INFO] Step 10/11 : EXPOSE ${EXPOSED_PORT}
[INFO] 
[ERROR] Invalid containerPort: 80+9001
[WARNING] An attempt failed, will retry 1 more times
org.apache.maven.plugin.MojoExecutionException: Could not build image

## What happened instead
If I do this in my command line:
docker build --build-arg EXPOSED_PORT="80 9001"-t mplescano/everest-reminder-server-oauth:1.1.0 .
Docker accepts my request.
## Software:

- docker version: Docker Tolbox version 18.03.0-ce, build 0520e24302
- dockerfile-maven-plugin version: 1.4.4
- maven version: 3.3.9

## Full backtrace

```
[INFO] Removing intermediate container a41bf2642ffa
[INFO]  ---> 93be35eee525
[INFO] Step 10/11 : EXPOSE ${EXPOSED_PORT}
[INFO] 
[ERROR] Invalid containerPort: 80+9001
[WARNING] An attempt failed, will retry 1 more times
org.apache.maven.plugin.MojoExecutionException: Could not build image
	at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:185)
	at com.spotify.plugin.dockerfile.BuildMojo.execute(BuildMojo.java:105)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.tryExecute(AbstractDockerMojo.java:259)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.execute(AbstractDockerMojo.java:248)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.spotify.docker.client.exceptions.DockerException: Invalid containerPort: 80+9001
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.handleError(LoggingProgressHandler.java:105)
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.progress(LoggingProgressHandler.java:63)
	at com.spotify.docker.client.DefaultDockerClient$BuildProgressHandler.progress(DefaultDockerClient.java:305)
	at com.spotify.docker.client.ProgressStream.tail(ProgressStream.java:77)
	at com.spotify.docker.client.DefaultDockerClient$ResponseTailReader.call(DefaultDockerClient.java:2734)
	at com.spotify.docker.client.DefaultDockerClient$ResponseTailReader.call(DefaultDockerClient.java:2718)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[INFO] Google Container Registry support is disabled
```

**Comment by ncouse** [comment]
This is a duplicate of #136, which is still open.
