### ISSUE TITLE
Pushing to Docker Hub doesn't work

### ISSUE THREAD

**Issue by rasmuslund** [spotify/dockerfile-maven#23]
How to reproduce:

- Log into dockerhub: `docker login docker.io`
- `/.docker/config.json` now looks like this:
`
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "..."
		}
	}
}
`
- When doing `mvn dockerfile:push`, I get a `com.spotify.docker.client.exceptions.DockerException: denied: requested access to the resource is denied`

Workaround:
- Modify `/.docker/config.json`, so the auths entry named `https://index.docker.io/v1/` is replaced with `docker.io`, like this:
`
{
	"auths": {
		"docker.io": {
			"auth": "..."
		}
	}
}
`

Full stack trace:
```
[INFO] The push refers to a repository [docker.io/schneiderelectricitb/appbackend]
...
[ERROR] denied: requested access to the resource is denied
[WARNING] An attempt failed, will retry 1 more times
org.apache.maven.plugin.MojoExecutionException: Could not push image
	at com.spotify.plugin.dockerfile.PushMojo.execute(PushMojo.java:90)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.tryExecute(AbstractDockerMojo.java:219)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.execute(AbstractDockerMojo.java:208)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.spotify.docker.client.exceptions.DockerException: denied: requested access to the resource is denied
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.handleError(LoggingProgressHandler.java:105)
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.progress(LoggingProgressHandler.java:63)
	at com.spotify.docker.client.ProgressStream.tail(ProgressStream.java:74)
	at com.spotify.docker.client.DefaultDockerClient.push(DefaultDockerClient.java:1274)
	at com.spotify.docker.client.DefaultDockerClient.push(DefaultDockerClient.java:1252)
	at com.spotify.plugin.dockerfile.PushMojo.execute(PushMojo.java:88)
	... 23 more
```

**Comment by ericdcobb** [comment]
I'm seeing the same thing, but I haven't been able to get your workaround to work. I'm on OSX, my config looks like:

```
{
        "auths": {
                "docker.io": {},
                "https://index.docker.io/v1/": {}
        },
        "credsStore": "osxkeychain"
}
```

**Comment by davidxia** [comment]
This should fix it. https://github.com/spotify/docker-client/pull/812

**Comment by arikkfir** [comment]
Workaround in bug description worked for me as well. Looking forward to the next version :)

**Comment by ErikCee** [comment]
Is it correct to reference https://github.com/spotify/dockerfile-maven/pull/38 as the fix for this bug? spotify/docker-client#812 wasn't included in version 8.8.0 if I understand correctly (and 1.3.3 which references 8.8.0 still contains the bug).

**Comment by mattnworb** [comment]
Thanks for the reminder @ErikCee , there needs to be a new release of docker-client and then this plugin too. I'll try to get both done today.

**Comment by mattnworb** [comment]
will be done in #47

**Comment by asaf** [comment]
@mattnworb Hey there,
I still get access denied when using `mvn dockerfile:push` while `docker push` works just fine with OSX, this issue should be resolved already?

thanks

**Comment by andreysaksonov** [comment]
@mattnworb looks like it still fails on default OSX configuration:

```
cat ~/.docker/config.json
{
	"auths": {
		"https://index.docker.io/v1/": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/17.12.0-ce (darwin)"
	},
	"credsStore": "osxkeychain"
}
```

**Comment by hariinfo** [comment]
changed config.json entry to and it worked after that

"auths": {
		"hub.docker.com": {}
	}
