### ISSUE TITLE
mvn dockerfile:push Access Denied

### ISSUE THREAD

**Issue by ProggerPete** [spotify/dockerfile-maven#235]
## Description

mvn dockerfile:push fails.

[ERROR] denied: requested access to the resource is denied
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 43.323 s
[INFO] Finished at: 2018-10-18T16:11:05+10:00
[INFO] Final Memory: 35M/425M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.7:push (default-cli) on project sightwords: Could not push image: denied: requested access to the resource is denied -> [Help 1]

It's worth noting that immediately after the failure I ran docker push manually and that works fine.

## How to reproduce

Run 

mvn dockerfile:push

It's possible this is a windows issue

## What do you expect

The image to get pushed successfully

## What happened instead

An error

## Software:

- `docker version`: Docker version 18.06.1-ce, build e68fc7a
- Spotify's dockerfile-maven version: 1.4.7

## Command output

PS C:\dev\react-boot> mvn dockerfile:build dockerfile:push
[INFO] Scanning for projects...
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in https://repo.spring.io/libs-snapshot was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in https://repo.spring.io/libs-snapshot was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building sightwords 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in https://repo.spring.io/libs-snapshot was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in https://repo.spring.io/libs-snapshot was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced
[INFO]
[INFO] --- dockerfile-maven-plugin:1.4.7:build (default-cli) @ sightwords ---
[INFO] Building Docker context C:\dev\react-boot
[INFO]
[INFO] Image will be built as peterwilkinson/sightwords:latest
[INFO]
[INFO] Step 1/5 : FROM openjdk:8-jre
[INFO]
[INFO] Pulling from library/openjdk
[INFO] Digest: sha256:bf7f911a70d6dd0d742bd86005cde04473b956e2ab14f3a099bb2d8da8442af5
[INFO] Status: Image is up to date for openjdk:8-jre
[INFO]  ---> 60648c86cfe8
[INFO] Step 2/5 : MAINTAINER Pete
[INFO]
[INFO]  ---> Using cache
[INFO]  ---> 475721e0222e
[INFO] Step 3/5 : ENTRYPOINT ["/usr/bin/java", "-jar", "/usr/share/sightwords/sightwords.jar"]
[INFO]
[INFO]  ---> Using cache
[INFO]  ---> 3a3eb51380d1
[INFO] Step 4/5 : ARG JAR_FILE
[INFO]
[INFO]  ---> Using cache
[INFO]  ---> 8d9d9e601103
[INFO] Step 5/5 : COPY target/${JAR_FILE} /usr/share/sightwords/sightwords.jar
[INFO]
[INFO]  ---> fca5daa36657
[INFO] Successfully built fca5daa36657
[INFO] Successfully tagged peterwilkinson/sightwords:latest
[INFO]
[INFO] Detected build of image with id fca5daa36657
[INFO] Building jar: C:\dev\react-boot\target\sightwords-0.0.1-SNAPSHOT-docker-info.jar
[INFO] Successfully built peterwilkinson/sightwords:latest
[INFO]
[INFO] --- dockerfile-maven-plugin:1.4.7:push (default-cli) @ sightwords ---
[INFO] The push refers to repository [docker.io/peterwilkinson/sightwords]
[INFO] Image f617195b9181: Preparing
[INFO] Image ceaed1136256: Preparing
[INFO] Image 923bc9a5d019: Preparing
[INFO] Image 185c62a48a71: Preparing
[INFO] Image d683471ab65a: Preparing
[INFO] Image 0f25831f224d: Preparing
[INFO] Image 08a01612ffca: Preparing
[INFO] Image 8bb25f9cdc41: Preparing
[INFO] Image f715ed19c28b: Preparing
[INFO] Image 0f25831f224d: Waiting
[INFO] Image 08a01612ffca: Waiting
[INFO] Image 8bb25f9cdc41: Waiting
[INFO] Image f715ed19c28b: Waiting
[ERROR] denied: requested access to the resource is denied
[WARNING] An attempt failed, will retry 1 more times
org.apache.maven.plugin.MojoExecutionException: Could not push image
        at com.spotify.plugin.dockerfile.PushMojo.execute(PushMojo.java:90)
        at com.spotify.plugin.dockerfile.AbstractDockerMojo.tryExecute(AbstractDockerMojo.java:259)
        at com.spotify.plugin.dockerfile.AbstractDockerMojo.execute(AbstractDockerMojo.java:248)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.spotify.docker.client.exceptions.DockerException: denied: requested access to the resource is denied
        at com.spotify.plugin.dockerfile.LoggingProgressHandler.handleError(LoggingProgressHandler.java:105)
        at com.spotify.plugin.dockerfile.LoggingProgressHandler.progress(LoggingProgressHandler.java:63)
        at com.spotify.docker.client.ProgressStream.tail(ProgressStream.java:77)
        at com.spotify.docker.client.DefaultDockerClient$ResponseTailReader.call(DefaultDockerClient.java:2734)
        at com.spotify.docker.client.DefaultDockerClient$ResponseTailReader.call(DefaultDockerClient.java:2718)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[INFO] The push refers to repository [docker.io/peterwilkinson/sightwords]
[INFO] Image f617195b9181: Preparing
[INFO] Image ceaed1136256: Preparing
[INFO] Image f617195b9181: Waiting
[INFO] Image 923bc9a5d019: Preparing
[INFO] Image 185c62a48a71: Preparing
[INFO] Image d683471ab65a: Preparing
[INFO] Image 0f25831f224d: Preparing
[INFO] Image 0f25831f224d: Waiting
[INFO] Image 923bc9a5d019: Waiting
[INFO] Image 185c62a48a71: Waiting
[INFO] Image d683471ab65a: Waiting
[INFO] Image ceaed1136256: Waiting
[INFO] Image 08a01612ffca: Preparing
[INFO] Image 08a01612ffca: Waiting
[INFO] Image 0f25831f224d: Waiting
[INFO] Image 8bb25f9cdc41: Preparing
[INFO] Image 8bb25f9cdc41: Waiting
[INFO] Image 08a01612ffca: Waiting
[INFO] Image f715ed19c28b: Preparing
[INFO] Image f715ed19c28b: Waiting
[INFO] Image 8bb25f9cdc41: Waiting
[INFO] Image f715ed19c28b: Waiting
[ERROR] denied: requested access to the resource is denied
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 43.323 s
[INFO] Finished at: 2018-10-18T16:11:05+10:00
[INFO] Final Memory: 35M/425M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.7:push (default-cli) on project sightwords: Could not push image: denied: requested access to the resource is denied -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
S C:\dev\react-boot> docker push peterwilkinson/sightwords
The push refers to repository [docker.io/peterwilkinson/sightwords]
f617195b9181: Pushed
ceaed1136256: Layer already exists
923bc9a5d019: Layer already exists
185c62a48a71: Layer already exists
d683471ab65a: Layer already exists
0f25831f224d: Layer already exists
08a01612ffca: Layer already exists
8bb25f9cdc41: Layer already exists
f715ed19c28b: Layer already exists
latest: digest: sha256:9735afeb88f4458290facfb0a04eac5e5bc9068395132e8b554d6400f3e1337c size: 2211

**Comment by Xartos** [comment]
I get the same problem. 
Tested this plugin for a couple of weeks ago with version 1.4.4 and it worked fine. Today I tried again (with the same config) and it didn't work (either on 1.4.4 or 1.4.7) and I get the exact same error as you get. 

I'm running on ubuntu 18.04 and `docker version`: 17.12.1-ce, build: 7390fc6

**Comment by seasonsolt** [comment]
same problem here
I got the same problem when I Authenticating with maven pom.xml
But it worked find with maven settings.xml

**Comment by Nalha** [comment]
Same issue, seems to work with 1.4.5 or older for me.

**Comment by soumik-dutta** [comment]
I am facing the same problem as well.
