### ISSUE TITLE
cross references in multi modules don't work

### ISSUE THREAD

**Issue by stoerr** [spotify/dockerfile-maven#261]
## Bug description

I'm trying to create several docker images with the dockerfile-maven-plugin , where the next one is created from the previous one. That works when calling docker directly, but not when I use the maven plugin. It seems the plugin tries to pull the previous image, instead of using the image built in the previous step, though `docker image ls` shows the image was built. It seems the integration test https://github.com/spotify/dockerfile-maven/tree/v1.4.9/plugin/src/it/multi-module was trying to test that kind of usage, but it's incomplete, and if I try to complete it, it doesn't work either.

## How to reproduce

Complete the multi-module test to build a chain of docker images by:
1. replacing https://github.com/spotify/dockerfile-maven/blob/master/plugin/src/it/multi-module/b/Dockerfile by

```
FROM test/multi-module-a:unstable
MAINTAINER David Flemström <dflemstr@spotify.com>
ENV foo=bar
```

and 2. integrate an actual call to the dockerfile-maven-plugin into https://github.com/spotify/dockerfile-maven/blob/master/plugin/src/it/multi-module/b/pom.xml :

```
      <plugin>
        <groupId>@project.groupId@</groupId>
        <artifactId>@project.artifactId@</artifactId>
        <version>@project.version@</version>
        <executions>
          <execution>
            <id>default</id>
            <goals>
              <goal>build</goal>
            </goals>
            <configuration>
              <repository>test/multi-module-b</repository>
              <tag>unstable</tag>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

## What do you expect

The multi-module/b should create a docker image and show up in `docker image ls` .

## Actual result

The build fails with a 
```
    org.apache.maven.plugin.MojoExecutionException: Could not build image
   Caused by: com.spotify.docker.client.exceptions.DockerException: pull access denied for test/multi-module-a, repository does not exist or may require 'docker login'
test/multi-module-a
```

while `docker image ls` actually shows `test/multi-module-a:unstable` was built. However, a `docker build .` in `multi-module/b` succeeds, so this is not a problem with `b/Dockerfile`.

## Software:

- `docker version`: 

Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
- Spotify's dockerfile-maven version: 1.49.0

## Full backtrace

```text
[INFO] [INFO] --- dockerfile-maven-plugin:1.4.10-SNAPSHOT:build (default) @ b ---
[INFO] [INFO] Building Docker context /Users/hps/dev/composum/dockersamples/dockerfile-maven/plugin/target/it/multi-module/b
[INFO] [INFO]
[INFO] [INFO] Image will be built as test/multi-module-a:unstable
[INFO] [INFO]
[INFO] [INFO] Step 1/3 : FROM test/multi-module-a:unstable
[INFO] [INFO]
[INFO] [ERROR] pull access denied for test/multi-module-a, repository does not exist or may require 'docker login'
[INFO] [WARNING] An attempt failed, will retry 1 more times
[INFO] org.apache.maven.plugin.MojoExecutionException: Could not build image
[INFO] 	at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:216)
[INFO] 	at com.spotify.plugin.dockerfile.BuildMojo.execute(BuildMojo.java:113)
[INFO] 	at com.spotify.plugin.dockerfile.AbstractDockerMojo.tryExecute(AbstractDockerMojo.java:265)
[INFO] 	at com.spotify.plugin.dockerfile.AbstractDockerMojo.execute(AbstractDockerMojo.java:254)
[INFO] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[INFO] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[INFO] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[INFO] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[INFO] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[INFO] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
[INFO] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
[INFO] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
[INFO] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
[INFO] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
[INFO] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] Caused by: com.spotify.docker.client.exceptions.DockerException: pull access denied for test/multi-module-a, repository does not exist or may require 'docker login'
[INFO] 	at com.spotify.plugin.dockerfile.LoggingProgressHandler.handleError(LoggingProgressHandler.java:105)
[INFO] 	at com.spotify.plugin.dockerfile.LoggingProgressHandler.progress(LoggingProgressHandler.java:63)
[INFO] 	at com.spotify.docker.client.DefaultDockerClient$BuildProgressHandler.progress(DefaultDockerClient.java:305)
[INFO] 	at com.spotify.docker.client.ProgressStream.tail(ProgressStream.java:77)
[INFO] 	at com.spotify.docker.client.DefaultDockerClient$ResponseTailReader.call(DefaultDockerClient.java:2734)
[INFO] 	at com.spotify.docker.client.DefaultDockerClient$ResponseTailReader.call(DefaultDockerClient.java:2718)
[INFO] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[INFO] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by stoerr** [comment]
Ah, sorry, I just found the dockerfile.build.pullNewerImage setting, which prevents that. Sorry for the trouble.

**Comment by stoerr** [comment]
BTW: it would be sensible if you extend the multi-module test as described, with the pullNewerImage=false . That would help people like me looking for examples and saved me quite some hours of hair pulling.

**Comment by stoerr** [comment]
I created a PR https://github.com/spotify/dockerfile-maven/pull/274 that extends the multi-module test as described. Perhaps that saves the next guy a couple of hours.
