### ISSUE TITLE
Cannot use private FROM image, access denied

### ISSUE THREAD

**Issue by viorica-visan1** [spotify/dockerfile-maven#288]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

When I use in FROM  an image from a private repository, I always get:
"[ERROR] pull access denied for viivvm/test, repository does not exist or may require 'docker login'"

The repository exists and the credentials are ok. 
I tried all 3 methods to authenticate:
> in maven settings
> in pom.xml 
> sending them as parameters 

All these methods work when I push an image (I had an image based on openjdk:8-jre, like in the documentation and I was able to build and push this image into the above private repository).
And I can use docker pull on the image.

## How to reproduce
in Dockerfile, FROM use an image from a private repository

## What do you expect

Given that I can authenticate and push an image, I expect I can also pull that image.

## What happened instead

The image cannot be pulled.

## Software:
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Mon May  6 13:59:26 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Mon May  6 13:59:26 2019
  OS/Arch:          linux/amd64
  Experimental:     false

1.4.10 
(I tried also some older releases like 1.3.6, same thing)

## Full backtrace

```text
[INFO] Step 1/6 : FROM viivvm/test:hello
[INFO] 
[ERROR] pull access denied for viivvm/test, repository does not exist or may require 'docker login'
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.025 s
[INFO] Finished at: 2019-05-08T14:11:38+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.3.1:build (default) on project test: Could not build image: pull access denied for viivvm/test, repository does not exist or may require 'docker login' -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:dockerfile-maven-plugin:1.3.1:build (default) on project test: Could not build image
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Could not build image
	at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:164)
	at com.spotify.plugin.dockerfile.BuildMojo.execute(BuildMojo.java:95)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.tryExecute(AbstractDockerMojo.java:219)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.execute(AbstractDockerMojo.java:208)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: com.spotify.docker.client.exceptions.DockerException: pull access denied for viivvm/test, repository does not exist or may require 'docker login'
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.handleError(LoggingProgressHandler.java:106)
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.progress(LoggingProgressHandler.java:64)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1389)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1348)
	at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:157)
	... 25 more
[ERROR] 
```

**Comment by ejschoen** [comment]
If it's helpful, I see the same error when trying to build off of a locally cached image (no registry specified in the FROM repo).  docker build . works, but mvn dockerfile:build does not.

**Comment by svalchinov** [comment]
Experiencing the same issue, any ideas?

**Comment by Yahvi007** [comment]
setting <pullNewerImage>false</pullNewerImage> will help to access the local images.
ref: https://github.com/spotify/dockerfile-maven/issues/171
