### ISSUE TITLE
dockerfile-maven-plugin 1.4.10 mvn docker:push error,but click the idea maven plugin dockerfile:push worked

### ISSUE THREAD

**Issue by JohnAddison** [spotify/dockerfile-maven#295]
\<artifactId\>helloworld\<\/artifactId\>
\<finalName\>${project.artifactId}\<\/finalName\>
\<configuration\>
                    \<contextDirectory\>${project.basedir}\<\/contextDirectory\>
                    \<useMavenSettingsForAuth\>true\<\/useMavenSettingsForAuth\>
                    \<repository\>${docker.registry.name.prefix}/${project.build.finalName}\<\/repository\>
                    \<tag\>${project.version}\<\/tag\>
                    \<buildArgs\>
                        \<JAR_FILE\>${project.build.finalName}.jar\<\/JAR_FILE\>
                    \<\/buildArgs\>
\</configuration\>

[INFO] Building jar: /Users/john/ws/springboot/helloworld/target/helloworld-docker-info.jar
[INFO] Successfully built johnaddison/helloworld:v1.0.1
[INFO] 
[INFO] --- docker-maven-plugin:1.2.0:push (default-cli) @ helloworld ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.333 s
[INFO] Finished at: 2019-06-09T15:09:38+08:00
[INFO] Final Memory: 58M/601M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:1.2.0:push (default-cli) on project helloworld: The parameters 'imageName' for goal com.spotify:docker-maven-plugin:1.2.0:push are missing or invalid -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:1.2.0:push (default-cli) on project helloworld: The parameters 'imageName' for goal com.spotify:docker-maven-plugin:1.2.0:push are missing or invalid
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginParameterException: The parameters 'imageName' for goal com.spotify:docker-maven-plugin:1.2.0:push are missing or invalid
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:641)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:594)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
[ERROR] 

if i use the cmd "mvn clean package && docker push johnaddison/helloworld:v1.0.1",worked

**Comment by JohnAddison** [comment]
sorry, the cmd i used is "mvn clean package docker:push", it should be "mvn clean package dockerfile:push"
