### ISSUE TITLE
ecr - no basic auth credentials push

### ISSUE THREAD

**Issue by casper5822** [spotify/dockerfile-maven#301]
**Is this a BUG REPORT or FEATURE REQUEST?**:

## Description

Problem pushing to ecr repository.
 If i use docker push  from command line it works, so i think it's not a docker or ecr authentication problem.

[Add feature/bug description here]

## How to reproduce
Just run a dockerfile:push on ecr repository with maven. 

## Software:

- `docker version`: 
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:56:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false

- Spotify's dockerfile-maven version: 1.4.10

## Full backtrace

```text
[INFO] Building WorkoutsMs 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- dockerfile-maven-plugin:1.4.10:push (default-cli) @ WorkoutsMs ---
[INFO] The push refers to repository [954469913757.dkr.ecr.eu-central-1.amazonaws.com/workoutms]
[INFO] Image fd181afae76e: Preparing
[INFO] Image 07086c7def57: Preparing
[INFO] Image 2c1286d30e6a: Preparing
[INFO] Image 6fe99072769a: Preparing
[INFO] Image 32d0fa94c161: Preparing
[INFO] Image 908c7cd4c567: Preparing
[INFO] Image ded0f21a9e89: Preparing
[INFO] Image d340e2271041: Preparing
[INFO] Image 4980e165b89a: Preparing
[INFO] Image 75e70aa52609: Preparing
[INFO] Image dda151859818: Preparing
[INFO] Image fbd2732ad777: Preparing
[INFO] Image ba9de9d8475e: Preparing
[INFO] Image 908c7cd4c567: Waiting
[INFO] Image ded0f21a9e89: Waiting
[INFO] Image d340e2271041: Waiting
[INFO] Image dda151859818: Waiting
[INFO] Image 4980e165b89a: Waiting
[INFO] Image fbd2732ad777: Waiting
[INFO] Image 75e70aa52609: Waiting
[INFO] Image ba9de9d8475e: Waiting
[ERROR] no basic auth credentials
[WARNING] An attempt failed, will retry 1 more times
org.apache.maven.plugin.MojoExecutionException: Could not push image
	at com.spotify.plugin.dockerfile.PushMojo.execute(PushMojo.java:90)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.tryExecute(AbstractDockerMojo.java:265)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.execute(AbstractDockerMojo.java:254)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.spotify.docker.client.exceptions.DockerException: no basic auth credentials
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.handleError(LoggingProgressHandler.java:105)
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.progress(LoggingProgressHandler.java:63)
	at com.spotify.docker.client.ProgressStream.tail(ProgressStream.java:77)
	at com.spotify.docker.client.DefaultDockerClient$ResponseTailReader.call(DefaultDockerClient.java:2734)
	at com.spotify.docker.client.DefaultDockerClient$ResponseTailReader.call(DefaultDockerClient.java:2718)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
[INFO] The push refers to repository [954469913757.dkr.ecr.eu-central-1.amazonaws.com/workoutms]
[INFO] Image fd181afae76e: Preparing
[INFO] Image 07086c7def57: Preparing
[INFO] Image 2c1286d30e6a: Preparing
[INFO] Image 6fe99072769a: Preparing
[INFO] Image 32d0fa94c161: Preparing
[INFO] Image 908c7cd4c567: Preparing
[INFO] Image ded0f21a9e89: Preparing
[INFO] Image d340e2271041: Preparing
[INFO] Image 4980e165b89a: Preparing
[INFO] Image 75e70aa52609: Preparing
[INFO] Image dda151859818: Preparing
[INFO] Image fbd2732ad777: Preparing
[INFO] Image ba9de9d8475e: Preparing
[INFO] Image ded0f21a9e89: Waiting
[INFO] Image 908c7cd4c567: Waiting
[INFO] Image dda151859818: Waiting
[INFO] Image d340e2271041: Waiting
[INFO] Image ba9de9d8475e: Waiting
[INFO] Image fbd2732ad777: Waiting
[INFO] Image 4980e165b89a: Waiting
[INFO] Image 75e70aa52609: Waiting
[ERROR] no basic auth credentials
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.631 s
[INFO] Finished at: 2019-07-08T20:56:37+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.10:push (default-cli) on project WorkoutsMs: Could not push image: no basic auth credentials -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

**Comment by oailloud** [comment]
I've got the exact same issue and it also works with the `docker push`.

Here's the output of my `docker version`:

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

and the pom of my last try:
```
            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>dockerfile-maven-plugin</artifactId>
                <version>1.4.10</version>
                <configuration>
                    <repository>${docker.image.prefix}/${docker.image.name}</repository>
                    <tag>${docker.image.tag}</tag>
                    <dockerfile>${docker.file}</dockerfile>
                    <useMavenSettingsForAuth>false</useMavenSettingsForAuth>
                    <buildArgs>
                        <JAR_FILE>target/${project.build.finalName}.jar</JAR_FILE>
                    </buildArgs>
                </configuration>
                <executions>
                    <execution>
                        <id>default</id>
                        <phase>install</phase>
                        <goals>
                            <goal>build</goal>
                            <goal>push</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
Any ideas?

**Comment by djgeary** [comment]
I have the exact same problem (not sure why this issue was closed). 

I've looked into it a bit and think the issue is the use of credsStore in my docker config.

My .docker/config.json looks like this (after an ECR login):

```
{
        "auths": {
                "xxxxxx.dkr.ecr.us-west-2.amazonaws.com": {}
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/19.03.5 (linux)"
        },
        "credsStore": "secretservice"
}
```

ie the actual credentials are stored in the "secretservice".
If I remove the line `"credsStore": "secretservice"` and re login to ECR the credentials appear in this file and `mvn deploy` works correctly without the error.

So the problem seems to be the spotify docker-client is not handling the docker config.json correctly. This problem looks like it was reported here https://github.com/spotify/docker-client/issues/1143, but the entire project is marked as being inactive and no longer updated. 
This project is stuck on the last version v8.16.0 of docker-client from May last year so I can't see how this will be resolved.

**Comment by codingtony** [comment]
Same issue here.

**Comment by praveenchandran** [comment]
I had the same issue. Backing up the docker config file and authorizing again worked. 

```
mv ~/.docker/config.json ~/.docker/config.json.bak
aws ecr get-login-password | docker login --username AWS --password-stdin REGISTRY_URL
```
