### ISSUE TITLE
tcp is not supported and also cannot work on jdk 11 or higher

### ISSUE THREAD

**Issue by Jovons** [spotify/dockerfile-maven#314]
On README, it says
>jdk 7 or higher. 

## TCP is not supported?

```
org.apache.http.impl.execchain.RetryExec execute
information: I/O exception (org.apache.http.conn.UnsupportedSchemeException) caught when processing request to {}->tcp://172.27.12.61:2376: tcp protocol is not supported
```
## JDK11 or higher does not have java.ee.se, so it throws:
```
java.lang.IllegalArgumentException: Errors were discovered while reifying SystemDescriptor(
        implementation=org.glassfish.jersey.message.internal.DataSourceProvider
        contracts={com.spotify.docker.client.shaded.javax.ws.rs.ext.MessageBodyReader,com.spotify.docker.client.shaded.javax.ws.rs.ext.MessageBodyWriter}
        scope=com.spotify.docker.client.shaded.javax.inject.Singleton
        qualifiers={}
        descriptorType=CLASS
        descriptorVisibility=NORMAL
        metadata=
        rank=0
        loader=org.glassfish.hk2.utilities.binding.AbstractBinder$2@6686d2d
        proxiable=null
        proxyForSameScope=null
        analysisName=null
        id=12
        locatorId=1
        identityHashCode=882059843
        reified=false)

```
Which is because:
```
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)

```

**Comment by mmaeller** [comment]
Add 

```
<dependency>
  <groupId>javax.activation</groupId>
  <artifactId>javax.activation-api</artifactId>
  <version>1.2.0</version>
</dependency>
```
to your dependencies. It's not part of the JDK anymore since 9+
