### ISSUE TITLE
Error when running open jdk11

### ISSUE THREAD

**Issue by benjefferies** [spotify/dockerfile-maven#316]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

## Description

```text
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.12:build (build) on project forgerock-openbanking-gateway: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.lang.UnsatisfiedLinkError: could not load FFI provider com.spotify.docker.client.shaded.jnr.ffi.provider.jffi.Provider: ExceptionInInitializerError: Can't overwrite cause with java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: /private/var/folders/2k/6q86kgm12sq9rxxvqp7d0c5c0000gn/T/jffi14387781516441958188.dylib: dlopen(/private/var/folders/2k/6q86kgm12sq9rxxvqp7d0c5c0000gn/T/jffi14387781516441958188.dylib, 1): no suitable image found.  Did find:
[ERROR]         /private/var/folders/2k/6q86kgm12sq9rxxvqp7d0c5c0000gn/T/jffi14387781516441958188.dylib: code signature in (/private/var/folders/2k/6q86kgm12sq9rxxvqp7d0c5c0000gn/T/jffi14387781516441958188.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```

## How to reproduce

`mvn install`

## What do you expect

Successful build

## What happened instead

UnsatisfiedLinkError

## Software:

- `docker version`:
	```
	Client: Docker Engine - Community
	 Version:           19.03.1
	 API version:       1.40
	 Go version:        go1.12.5
	 Git commit:        74b1e89
	 Built:             Thu Jul 25 21:18:17 2019
	 OS/Arch:           darwin/amd64
	 Experimental:      false
	
	Server: Docker Engine - Community
	 Engine:
	  Version:          19.03.1
	  API version:      1.40 (minimum version 1.12)
	  Go version:       go1.12.5
	  Git commit:       74b1e89
	  Built:            Thu Jul 25 21:17:52 2019
	  OS/Arch:          linux/amd64
	  Experimental:     false
	 containerd:
	  Version:          v1.2.6
	  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
	 runc:
	  Version:          1.0.0-rc8
	  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
	 docker-init:
	  Version:          0.18.0
	  GitCommit:        fec3683
	```
- Spotify's dockerfile-maven version: 1.4.12
- Maven/Java
```
		Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T19:49:05Z)
		Maven home: /usr/local/Cellar/maven/3.5.3/libexec
		Java version: 11.0.4, vendor: AdoptOpenJDK
		Java home: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
		Default locale: en_GB, platform encoding: UTF-8
		OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
		```
## Full backtrace

```text
Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.lang.UnsatisfiedLinkError: could not load FFI provider com.spotify.docker.client.shaded.jnr.ffi.provider.jffi.Provider: ExceptionInInitializerError: Can't overwrite cause with java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: /private/var/folders/2k/6q86kgm12sq9rxxvqp7d0c5c0000gn/T/jffi14387781516441958188.dylib: dlopen(/private/var/folders/2k/6q86kgm12sq9rxxvqp7d0c5c0000gn/T/jffi14387781516441958188.dylib, 1): no suitable image found.  Did find:
[ERROR]         /private/var/folders/2k/6q86kgm12sq9rxxvqp7d0c5c0000gn/T/jffi14387781516441958188.dylib: code signature in (/private/var/folders/2k/6q86kgm12sq9rxxvqp7d0c5c0000gn/T/jffi14387781516441958188.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
[ERROR]         at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
[ERROR]         at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
[ERROR]         at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
[ERROR]         at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
[ERROR]         at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
[ERROR]         at java.base/java.lang.Runtime.load0(Runtime.java:767)
[ERROR]         at java.base/java.lang.System.load(System.java:1831)
[ERROR]         at com.kenai.jffi.internal.StubLoader.loadFromJar(StubLoader.java:371)
[ERROR]         at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:258)
[ERROR]         at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:444)
[ERROR]         at java.base/java.lang.Class.forName0(Native Method)
[ERROR]         at java.base/java.lang.Class.forName(Class.java:398)
[ERROR]         at com.kenai.jffi.Init.load(Init.java:68)
[ERROR]         at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:49)
[ERROR]         at com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:45)
[ERROR]         at com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
[ERROR]         at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
[ERROR]         at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
[ERROR]         at com.kenai.jffi.Type.resolveSize(Type.java:155)
[ERROR]         at com.kenai.jffi.Type.size(Type.java:138)
[ERROR]         at com.spotify.docker.client.shaded.jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:187)
[ERROR]         at com.spotify.docker.client.shaded.jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
[ERROR]         at com.spotify.docker.client.shaded.jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:66)
[ERROR]         at com.spotify.docker.client.shaded.jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:41)
[ERROR]         at com.spotify.docker.client.shaded.jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:62)
[ERROR]         at com.spotify.docker.client.shaded.jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:58)
[ERROR]         at com.spotify.docker.client.shaded.jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
[ERROR]         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR]         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[ERROR]         at java.base/java.lang.Class.newInstance(Class.java:584)
[ERROR]         at com.spotify.docker.client.shaded.jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
[ERROR]         at com.spotify.docker.client.shaded.jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
[ERROR]         at com.spotify.docker.client.shaded.jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
[ERROR]         at com.spotify.docker.client.shaded.jnr.ffi.LibraryLoader.create(LibraryLoader.java:73)
[ERROR]         at com.spotify.docker.client.shaded.jnr.unixsocket.Native.<clinit>(Native.java:76)
[ERROR]         at com.spotify.docker.client.shaded.jnr.unixsocket.UnixSocketChannel.<init>(UnixSocketChannel.java:101)
[ERROR]         at com.spotify.docker.client.shaded.jnr.unixsocket.UnixSocketChannel.open(UnixSocketChannel.java:60)
[ERROR]         at com.spotify.docker.client.UnixConnectionSocketFactory.createSocket(UnixConnectionSocketFactory.java:69)
[ERROR]         at com.spotify.docker.client.UnixConnectionSocketFactory.createSocket(UnixConnectionSocketFactory.java:44)
[ERROR]         at com.spotify.docker.client.shaded.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:118)
[ERROR]         at com.spotify.docker.client.shaded.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
[ERROR]         at com.spotify.docker.client.shaded.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
[ERROR]         at com.spotify.docker.client.shaded.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
[ERROR]         at com.spotify.docker.client.shaded.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
[ERROR]         at com.spotify.docker.client.shaded.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
[ERROR]         at com.spotify.docker.client.shaded.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
[ERROR]         at com.spotify.docker.client.shaded.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[ERROR]         at com.spotify.docker.client.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
[ERROR]         at com.spotify.docker.client.shaded.org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
[ERROR]         at com.spotify.docker.client.shaded.org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
[ERROR]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[ERROR]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[ERROR]         at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
[ERROR]         at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
[ERROR]         at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
[ERROR]         at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
[ERROR]         at com.spotify.docker.client.shaded.org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
[ERROR]         at com.spotify.docker.client.shaded.org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:178)
[ERROR]         at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
[ERROR]         at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
[ERROR]         at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:315)
[ERROR]         at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:297)
[ERROR]         at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:267)
[ERROR]         at com.spotify.docker.client.shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
[ERROR]         at com.spotify.docker.client.shaded.org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
[ERROR]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[ERROR]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[ERROR]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[ERROR]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834
```

**Comment by benjefferies** [comment]
This was using adoptopenjdk https://github.com/AdoptOpenJDK/homebrew-openjdk. Updating to https://jdk.java.net/12/ fixed this issue
