### ISSUE TITLE
Could not build image: java.io.IOException: request to write '8192' bytes exceeds size...

### ISSUE THREAD

**Issue by tbrouhier** [spotify/dockerfile-maven#32]
Hi,

We are investigating the build of Docker images inside of Docker and are stuck by an IOException. 
The project is a simple Spring Boot hello-world (equivalent of the ones found on their site) with a really straightforward Dockerfile. It builds perfectly on my local host (ubuntu 16.04, openjdk-8, docker 1.12) but fails as soon as it builds inside a Docker container (dind). However, building the app (mvn clean package) and docker image (docker build -t ...) separately in the dind does work. 

You will find the error log as well as the Dockefile of the dind/java container below.

Have you ever experienced this issue? Could you help us understand this behavior?

Many thanks in advance,
Thomas

_Maven build log:_

```
org.apache.maven.plugin.MojoExecutionException: Could not build image
        at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:164)
        at com.spotify.plugin.dockerfile.BuildMojo.execute(BuildMojo.java:95)
        at com.spotify.plugin.dockerfile.AbstractDockerMojo.tryExecute(AbstractDockerMojo.java:219)
        at com.spotify.plugin.dockerfile.AbstractDockerMojo.execute(AbstractDockerMojo.java:208)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.io.IOException: request to write '8192' bytes exceeds size in header of '12960433' bytes for entry 'docker-client-7093082277195045664.tar.gz'
        at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.write(TarArchiveOutputStream.java:377)
        at java.nio.file.Files.copy(Files.java:2909)
        at java.nio.file.Files.copy(Files.java:3069)
        at com.spotify.docker.client.CompressedDirectory$Visitor.visitFile(CompressedDirectory.java:302)
        at com.spotify.docker.client.CompressedDirectory$Visitor.visitFile(CompressedDirectory.java:252)
        at java.nio.file.Files.walkFileTree(Files.java:2670)
        at com.spotify.docker.client.CompressedDirectory.create(CompressedDirectory.java:114)
        at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1373)
        at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1348)
        at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:157)
        ... 25 more
        Suppressed: java.io.IOException: This archives contains unclosed entries.
                at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:220)
                at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.close(TarArchiveOutputStream.java:236)
                at com.spotify.docker.client.CompressedDirectory.create(CompressedDirectory.java:119)
                ... 28 more
```

_Dockerfile dind/java_:
```
FROM docker:stable-dind
ENV LANG C.UTF-8

RUN { \
        echo '#!/bin/sh'; \
        echo 'set -e'; \
        echo; \
        echo 'dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"'; \
    } > /usr/local/bin/docker-java-home \
    && chmod +x /usr/local/bin/docker-java-home
ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
ENV PATH $PATH:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin

ENV JAVA_VERSION 8u121
ENV JAVA_ALPINE_VERSION 8.121.13-r0

RUN set -x \
    && apk add --no-cache \
        openjdk8="$JAVA_ALPINE_VERSION" \
&& [ "$JAVA_HOME" = "$(docker-java-home)" ]
```

**Comment by davidxia** [comment]
I'm unable to repro with the Dockerfile above and

```java

    final Path pwd = Paths.get(".");
    final AtomicReference<String> imageIdFromMessage = new AtomicReference<>();
    try {
      final String returnedImageId = docker.build(pwd.toAbsolutePath(), "dind/java:test",
          new ProgressHandler() {
        @Override
        public void progress(ProgressMessage message) throws DockerException {
          final String imageId = message.buildImageId();
          if (imageId != null) {
            imageIdFromMessage.set(imageId);
          }
        }
      });
      System.out.println("Docker image created. Returned: " + returnedImageId);
    } catch (DockerException | InterruptedException | IOException e) {
      System.out.println("Exception building the image! " + e);
    }
```

(Strangely, `returnedImageId` is null...)

**Comment by tbrouhier** [comment]
Thanks for your answer. 

In the meantime, we moved away from the dind approach and went for mounting the socket as a volume.

**Comment by davidxia** [comment]
That sounds like a much better approach for this.
-- 
David Xia
Software Engineer
dxia@spotify.com
