### ISSUE TITLE
Error: Host name may not be null

### ISSUE THREAD

**Issue by thiagolealassis** [spotify/dockerfile-maven#94]
When i execute mvn dockerfile:build everything goes fine, but when i attach the execution to maven lifecycle ex:

				<plugin>
					<groupId>com.spotify</groupId>
					<artifactId>dockerfile-maven-plugin</artifactId>
					<version>${dockerfile.maven.plugin.version}</version>
		                       <executions>
                        		   <execution>
                            		   <id>default</id>
                            		   <goals>
                                		   <goal>build</goal>
                                		   <goal>push</goal>
                            		   </goals>
                        		   </execution>
                    		        </executions>
					<configuration>
						<contextDirectory>${project.build.directory}</contextDirectory>
						<repository>${docker.repository}</repository>
						<tag>${project.version}</tag>
						<buildArgs>
							<JAR_FILE>${project.build.finalName}.jar</JAR_FILE>
						</buildArgs>
					</configuration>
				</plugin>

I got the error: [ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.3.6:build (default) on project fusion-demo-backend: Execution default of goal com.spotify:dockerfile-maven-plugin:1.3.6:build failed: Host name may not be null -> [Help 1]

Can anybody help-me ? Thanks

**Comment by ytheohar** [comment]
I have the same. 
Debugging the plugin code I found that the plugin does not honour the -Dhttp.nonProxyHosts setting.
The problem lies in the DefaultDockerClient.updateProxy() method. If the "http.proxyHost" is set it uses the proxy without looking at if the "http.nonProxyHosts" setting includes the docker host.

Therefore, to be honest it looks more like a bug of "docker-client" project.

Temporary solution until the bug is fixed is to unset the http.proxyHost setting. You could have set this in the env variable _JAVA_OPTIONS or MAVEN_OPTS.

**Comment by davidkarlsen** [comment]
I experience the same - but only in a multi-module build, if I cd into the module and build it there (and attached to lifecycle) it works fine.

**Comment by beskow** [comment]
This is actually a problem both in the  "docker-client" project (where http.nonProxyHosts is not honored, see https://github.com/spotify/docker-client/issues/978) and in dockerfile-maven, where http.nonProxyHosts is not properly set when running attached to the maven lifecycle.

As I understand it, when executing within the maven lifecycle, some of the proxy configuration from settings.xml is read (to set http.proxyHost, http.proxyPort, http.proxyUser and http.proxyPassword System properties). Since version 8.9.1 of "docker-client", the http.proxyHost by default is used if set, hence dockerfile-maven is affected.

This new behavior of "docker-client" to use a proxy if set, can be turned off using a property on the builder. Hence the easy fix is to add the same property "useProxy" to dockerfile-maven (with default value false), to allow proxy useage to be turned off. I have issued a pull request for this (https://github.com/spotify/dockerfile-maven/pull/150).

Now, for the long-term solution:

I have issued a pull request to the  "docker-client" project, which will hopefully be included in next version.

Now, this unfortunately doesn't solve the problem for dockerfile-maven, since the http.nonProxyHosts for some reason is not read from settings.xml and set as a system property. This is a known problem, fixed locally in other plugins (see e.g. https://issues.apache.org/jira/browse/CXF-4710).

Hence my second pull request includes a fix for this behavior as well (inspired by the CFX fix above), which if useProxy is set reads the settings.xml and populates all relevant system properties for http proxy usage (and restores previous values after execution).

**Comment by Tzrlk** [comment]
Using 1.4.1 including the changes merged in #150, I'm still getting the error even after adding `<useProxy>false</useProxy>` to the plugin configuration. Here's my plugin configuration for reference:

```xml
<plugin>
	<groupId>com.spotify</groupId>
	<artifactId>dockerfile-maven-plugin</artifactId>
	<version>1.4.1</version>
	<configuration>
		<useProxy>false</useProxy>
		<useMavenSettingsForAuth>true</useMavenSettingsForAuth>
		<repository>${docker.registry}/${docker.reponame}</repository>
		<tag>${project.version}</tag>
		<buildArgs>
			<APP_JAR>target/${project.build.finalName}.jar</APP_JAR>
		</buildArgs>
	</configuration>
	<executions>

		<execution>
			<id>docker-build</id>
			<phase>package</phase>
			<goals>
				<goal>build</goal>
				<goal>tag</goal>
			</goals>
		</execution>

		<execution>
			<id>docker-push</id>
			<phase>deploy</phase>
			<goals>
				<goal>push</goal>
			</goals>
		</execution>

	</executions>
</plugin>
```

And here's the stacktrace output from maven:
```bash
org.apache.maven.plugin.MojoExecutionException: Could not build image
	at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:185)
	at com.spotify.plugin.dockerfile.BuildMojo.execute(BuildMojo.java:105)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.tryExecute(AbstractDockerMojo.java:252)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.execute(AbstractDockerMojo.java:241)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.lang.IllegalArgumentException: Host name may not be null
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2710)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2641)
	at com.spotify.docker.client.DefaultDockerClient.version(DefaultDockerClient.java:517)
	at com.spotify.docker.client.DefaultDockerClient.authRegistryHeader(DefaultDockerClient.java:2753)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1414)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1383)
	at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:178)
	... 26 more
Caused by: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.lang.IllegalArgumentException: Host name may not be null
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2639)
	... 31 more
Caused by: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.lang.IllegalArgumentException: Host name may not be null
	at com.spotify.docker.client.shaded.org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:178)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Host name may not be null
	at com.spotify.docker.client.shaded.org.apache.http.util.Args.containsNoBlanks(Args.java:81)
	at com.spotify.docker.client.shaded.org.apache.http.HttpHost.<init>(HttpHost.java:81)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.apache.connector.ApacheConnector.getHost(ApacheConnector.java:514)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
	... 21 more
```

**Comment by davidxia** [comment]
@Tzrlk, you're right. The required docker-client changes weren't in the previous release. Please try with the latest release of 1.4.2 and let me know.

**Comment by Tzrlk** [comment]
Debugged through the plugin code, and it looks as though I have a completely different problem. Because I'm running on Windows, the `WebTarget` passed into `DefaultDockerClient#request(...)` references the `npipe:////./pipe/docker_engine` url derived from the `DOCKER_HOST` environment variable. As soon as I overrode that, I started getting a completely different authorisation problem.

If the plugin is unable to deal with windows named pipes, or unix sockets (haven't tested that one), then there should probably be a routine fairly early on in the process to detect the content of `DOCKER_HOST` and warn the user that they need to use a `tcp://localhost:2375` url. The code block at `DefaultDockerClient:399` should be able to take another branch.
